# Generated by Django 3.2.8 on 2021-10-19 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0002_bookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
