# Generated by Django 3.2.8 on 2021-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_rename_city_citymodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='jobs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
