# Generated by Django 3.2.8 on 2021-11-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0006_auto_20211106_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.countrymodel'),
        ),
    ]
