# Generated by Django 3.2.8 on 2021-11-06 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_alter_personmodel_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_bar', models.CharField(max_length=50)),
                ('by_country', models.BooleanField(default=False)),
                ('by_age', models.BooleanField(default=False)),
                ('by_job', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 39, 45, 220135)),
        ),
    ]
