# Generated by Django 3.2.8 on 2021-11-06 17:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_auto_20211106_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='can_donate_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 46, 12, 403888)),
        ),
    ]
