# Generated by Django 3.2.8 on 2021-11-07 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_auto_20211106_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='last_name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 16, 54, 31, 57508)),
        ),
    ]
