# Generated by Django 3.2.8 on 2021-11-07 14:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_auto_20211107_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='personal',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Personal Identification Number'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 17, 2, 56, 554349)),
        ),
    ]
