# Generated by Django 3.2.8 on 2021-11-08 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0012_auto_20211107_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='marital_status',
            field=models.JSONField(default={'Gender': 'None', 'Marital Status': 'Single'}),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 20, 31, 52, 503070)),
        ),
    ]
