# Generated by Django 3.2.8 on 2021-11-08 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0014_auto_20211108_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='gender',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 20, 49, 57, 524734)),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='marital_status',
            field=models.JSONField(default={'MaritalStatus': 'Single'}),
        ),
    ]
