# Generated by Django 3.2.8 on 2021-11-08 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0015_auto_20211108_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='gender',
            new_name='pet',
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 22, 33, 39, 302117)),
        ),
    ]
