# Generated by Django 3.2.8 on 2021-11-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0017_auto_20211109_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogmodel',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 12, 15, 13, 248240)),
        ),
    ]
