# Generated by Django 3.2.8 on 2022-01-11 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0025_alter_personmodel_last_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 17, 54, 47, 245242)),
        ),
    ]
