# Generated by Django 3.2.8 on 2022-01-12 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0026_alter_personmodel_last_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='last_donated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 1, 4, 58, 429875)),
        ),
    ]
