# Generated by Django 3.2.8 on 2021-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
