# Generated by Django 3.2.8 on 2021-12-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_userinput_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
