# Generated by Django 3.2.8 on 2021-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_userinput_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
